### ISSUE TITLE
Option to disable failing builds during kubechecks failures

### ISSUE THREAD

**Issue by MeNsaaH** [zapier/kubechecks#117]
consider adding some variable that configures what should make kubechecks fail in pipeline. KUBECHECKS_FAIL_PIPELINE_ON_KUBEPUG, KUBECHECKS_FAIL_PIPELINE_ON_ERROR , KUBECHECKS_FAIL_ON_KUBECONFORM_REPORT

**Comment by djeebus** [comment]
I snuck the resolution into #163 :flushed:
