### ISSUE TITLE
Kubeconform Alternate schema locations

### ISSUE THREAD

**Issue by s3than** [zapier/kubechecks#234]
:wave: 

I'm looking at adding this as a schema location

```
$ kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' [MANIFEST]
```

I notice however that the ability to add additional schema locations is tied to the following 

https://github.com/zapier/kubechecks/blob/main/pkg/checks/kubeconform/validate.go#L60C1-L62C30

Thank you

**Comment by s3than** [comment]
An alternative would be to enable the addition of this repo https://github.com/datreeio/CRDs-catalog by flag etc :bow:

**Comment by pauloconnor** [comment]
Duplicate of https://github.com/zapier/kubechecks/issues/169 ?

**Comment by s3than** [comment]
Duplicate thanks @pauloconnor
