### ISSUE TITLE
Question: discovery of related ArgocD apps

### ISSUE THREAD

**Issue by reggie-k** [zapier/kubechecks#281]
How are the ArgoCD apps that would be affected by a code change in a PR are discovered?

**Comment by djeebus** [comment]
Good question! 
1. Assuming you've got argocd app monitoring enabled via `KUBECHECKS_MONITOR_ALL_APPLICATIONS`, kubechecks pulls all application and application sets, and creates a map apps to files and folders.
2. When a pull request comes in, all changed files are processed against that map, and kubechecks figures out which applications have been modified.
3. It also checks the root of the repo for a file called `.kubechecks.yml` for paths and application names, but this is mostly obsolete now that argocd applications are directly monitored.
