### ISSUE TITLE
Unable to enable KUBECHECKS_MONITOR_ALL_APPLICATIONS

### ISSUE THREAD

**Issue by joelp172** [zapier/kubechecks#296]
I have KubeChecks running and setup on a local MiniKube cluster along with argocd for testing and eval. I have the svcs exposed on some dev urls.

If I set `KUBECHECKS_MONITOR_ALL_APPLICATIONS: false` kuebchecks starts sucessfully

```
5:22PM INF ArgoCD client configuration auth-token=199 grpc-web-root-path= insecure=false server-addr=https://argocd.myurl-dev.co.uk
5:22PM INF not monitoring applications, MonitorAllApplications: false
5:22PM INF initializing git settings
5:22PM INF Initializing telemetry
5:22PM INF otel disabled
5:22PM INF starting web server
5:22PM INF listening for requests
Method	Path
GET	/ready
GET	/live
GET	/metrics
POST	/hooks/github/project
5:22PM ??? ⇨ http server started on [::]:8080
```

I can send PRs to the webhook and it receives them fine.

However, if I set  `KUBECHECKS_MONITOR_ALL_APPLICATIONS: true` I get the following error:

```
could not create ArgoCD Application Client error="dial tcp: address tcp///argocd.myurl-dev.co.uk: unknown port"
```

Its also the same if I use internal cluster addresses. Is there some config I am missing?

**Comment by djeebus** [comment]
It looks like you need `<host>:<port>`, not `<protocol>://<host>`. so instead of `https://argocd.myurl-dev.co.uk`, you want `argocd.myurl-dev.co.uk:443`. We could do a better job of validating that's set correctly, but it's how argocd's sdk expects you to pass the address

**Comment by mvineza** [comment]
> you want argocd.myurl-dev.co.uk:443

I tried this format but the pod returns:
```
11:42PM FTL could not create ArgoCD Application Client error="tls: failed to verify certificate: x509: certificate signed by unknown authority"
```
So I set `KUBECHECKS_ARGOCD_API_INSECURE: "true"`. But pod is now returning a different error.
```
11:43PM FTL could not create ArgoCD Application Client error="credentials: cannot check peer: missing selected ALPN property"
```

**Comment by mvineza** [comment]
That worked @djeebus , thanks!
