### ISSUE TITLE
No apps found

### ISSUE THREAD

**Issue by mvineza** [zapier/kubechecks#306]
Hi there, first of all thank you for this tool! I'm trying this on our gitlab repositories but encountering this [error](https://github.com/zapier/kubechecks/blob/35dfcf6cf96c66d4893be723f5db45ebd629b047/pkg/affected_apps/argocd_matcher.go#L40) from debug logs.
```
4:52AM DBG found 0 apps
4:52AM DBG creating fs for /tmp/kubechecks-repo-1324045563
4:52AM DBG following kustomize apps
4:52AM DBG found 0 apps
4:52AM DBG looking for https://project_9000_bot_xyz@gitlab.local/shared-infrastructure/iac/argocd/inf-core-services repos
4:52AM DBG found 0 appSets
```
I'm using `v0.4.5` helm chart which pulls `v1.8.0`. My config is:
```
  KUBECHECKS_ARGOCD_API_NAMESPACE: argocd
  KUBECHECKS_ARGOCD_API_PATH_PREFIX: /
  KUBECHECKS_ARGOCD_API_SERVER_ADDR: https://argocd.local
  KUBECHECKS_ARGOCD_API_TOKEN: <token>
  KUBECHECKS_ARGOCD_WEBHOOK_URL: https://argocd.local/api/webhook
  KUBECHECKS_LOG_LEVEL: trace
  KUBECHECKS_VCS_BASE_URL: https://gitlab.local
  KUBECHECKS_VCS_TYPE: gitlab
  KUBECHECKS_WEBHOOK_URL_BASE: https://kubechecks.local
```
Not entirely sure if this has something to do with the layout of our repository (helm repo) which is something like:
```
apps/{namespace}/{app_name}/{charts,values.yaml,templates,Chart.yaml}
```
I tried to add an `app1.yaml` file on the root of repo consisting of `Application` resource and it produced a different message which is telling me it detected an application. But partly it still says `found 0 apps`.
```
4:56AM DBG found 0 apps
...
4:56AM DBG change: app1.yaml
```
I probably just doing something silly that I missed from the docs.

**Comment by djeebus** [comment]
I suspect you also need `KUBECHECKS_MONITOR_ALL_APPLICATIONS: "true"`. This was an experimental opt-in feature, but it seems quite stable at this point, and will probably become the default in the next major release.

**Comment by mvineza** [comment]
Hi @djeebus , thanks for looking.  I tried that but encounterd this issue.

https://github.com/zapier/kubechecks/issues/296#issuecomment-2469299129

I tried different combinations of settings but everytime it produced a different error so I didn't investigate further thinking I might going to a rabbit hole/wrong direction.

**Comment by djeebus** [comment]
It sounds like you were on the right track. If you don't have a valid TLS cert on your argocd endpoint, you'll have to disable some security features. There's an extra env var that the grpc library now requires to disable some features that's mentioned in the MR you linked (added since you last looked, I believe). Mind trying that, and if it doesn't work, report the errors back here?

**Comment by mvineza** [comment]
Hi @djeebus , yes as per our conversation in this [post](https://github.com/zapier/kubechecks/issues/296#issuecomment-2523831059), the `GRPC_ENFORCE_ALPN_ENABLED` worked. Thanks!
