### ISSUE TITLE
Release 1.9.0

### ISSUE THREAD

**Issue by DrFaust92** [zapier/kubechecks#330]
Hi, can we cut a new version please? there are some feature we are waiting for a while that have been recently merged and we would love to use those.

**Comment by djeebus** [comment]
Working on it! There's one or two more features we're going to merge shortly, then release a 2.0 release (mostly to advertise that there are some [new requirements](https://github.com/zapier/kubechecks/pull/298) with regards to network connectivity. Stay tuned!
