### ISSUE TITLE
Kubechecks calls gitlab.com instead of privately hosted VCS

### ISSUE THREAD

**Issue by bauerjs1** [zapier/kubechecks#50]
Hey there,

Kubechecks looks like a really nice tool to me and I'd love to get it to work. I tried deploying Kubechecks via Helm, and not all of the [Kubecheck's ENVs](https://kubechecks.readthedocs.io/en/stable/usage/) are clear to me. The container is still failing with the error message

```
FTL could not create Gitlab token user error="GET https://gitlab.com/api/v4/user: 401 {message: 401 Unauthorized}"
```

I am not sure what Kubecheck tries to do at this point but I need it to work with our local GitLab installation, whose base URL I have configured in `KUBECHECKS_WEBHOOK_URL_BASE` (_"The URL where KubeChecks receives webhooks from"_). Does Kubecheck support local GitLab instances at this point?

Cheers

**Comment by djeebus** [comment]
Whoops, yup, definitely missed that. [This](https://github.com/zapier/kubechecks/pull/51) should get us that support though.

**Comment by djeebus** [comment]
The `KUBECHECKS_WEBHOOK_URL_BASE` env var is the url that, for example, gitlab should send their webhook requests in order to trigger kubechecks. I'm going to see if I can make that documentation a little less obtuse, it's definitely confusing.

**Comment by bauerjs1** [comment]
Great, thanks a lot!

Maybe a clearer description would be something like _"The endpoint to listen on for incoming PR/MR event webhooks"_?

**Comment by bauerjs1** [comment]
I have tried so set up Kubechecks with the `dev` image containing your latest changes but I am still not getting it to work completely. Currently, it fails while trying to clone the repo:
```
4:21PM ERR unable to clone repository, Cloning into '/tmp/kubechecks-mr-clone1436125826'...
fatal: could not read Username for 'https://git.mycompany.com': No such device or address
 error="exit status 128"
4:21PM ERR unable to clone repo locally error="exit status 128"
```
The `could not read Username` error could mean that at this point, there might be some credential helper missing or something. However it took me to [this](https://github.com/zapier/kubechecks/blob/main/pkg/repo/repo.go#L234) line, which also looks like it is still hard-coded to gitlab.com:
```go
cmd = exec.Command("echo", fmt.Sprintf("https://%s:%s@%s.com", user, viper.GetString("vcs-token"), viper.GetString("vcs-type")))
```
I am not sure though, if that is the cause of the  `could not read Username` error.

**Comment by djeebus** [comment]
Ah, good catch, that hardcoded `.com` does indicate there's some weird url hackery going on there. Let me try and clean that up real quick. Thanks for the debugging effort!

**Comment by djeebus** [comment]
@bauerjs1 mind taking a look at the pr image built in #55 and see if that works for you?

**Comment by bauerjs1** [comment]
@djeebus sure, it's just that I am on holidays 🙃 Right now, the image is not available, anymore. I might have one more chance tomorrow, after that I am out for a couple of weeks...

**Comment by bauerjs1** [comment]
@djeebus I am back and happy to test your changes. From Monday on, I will check back regularly for an available test build.
Cheers

**Comment by djeebus** [comment]
Should be back up; let me know how it goes?

**Comment by bauerjs1** [comment]
Looks like this fixes the issue. Kubechecks calls the correct GitLab and is able to retrieve its user info and post comments in the MR 👍🏻 

Thanks a lot! :)
