### ISSUE TITLE
HorizontalPodAutoscaler v2beta1 is deprecated in v1.22+ and removed in v1.25

### ISSUE THREAD

**Issue by sl1pm4t** [zapier/kubechecks#58]
It's not possible to enable autoscaling of kubechecks on a v1.25+ Kubernetes clusters, because the chart uses the `HorizontalPodAutoscaler v2beta1` API which has been removed.

**Comment by djeebus** [comment]
Oh, good call. We should probably add some [helm fanciness](https://helm.sh/docs/chart_template_guide/function_list/#capabilitiesapiversionshas) to swap the versions
