### ISSUE TITLE
Can't Pull most of the image tags from ghcr.io

### ISSUE THREAD

**Issue by ymedlop** [zapier/kubechecks#88]
Hi,

when attempting to pull the image I get the following error:
![image](https://github.com/zapier/kubechecks/assets/5522922/35e497d2-e6ad-47b1-b48f-89930bd9ebda)

I have the same errors with other tags. 
![image](https://github.com/zapier/kubechecks/assets/5522922/a3860ada-64d1-43c6-9beb-8e548f5e4eeb)

The only one I have successfully pulled was this one:
![image](https://github.com/zapier/kubechecks/assets/5522922/9addfc34-c148-48be-9245-3f7869c32db3)

**Comment by djeebus** [comment]
Ah, looks like we've had some issues w/ multiarch images. I think I've got them sorted out for the most recent image (v1.2.0), can you give that a shot?

**Comment by ymedlop** [comment]
Hi,

Looks like I have the same error for tag v1.2.0.
<img width="586" alt="Captura de pantalla 2023-12-19 a las 21 30 56" src="https://github.com/zapier/kubechecks/assets/5522922/b4da9435-6ce9-4cb9-b734-0c9a052a736b">

**Comment by djeebus** [comment]
whew. ok, figured it out. turns out that our maintenance script was wiping out layers that were referenced by the manifest, since they were untagged. i've rebuilt 1.2.0 and 1.3.0, we should be good now.

**Comment by ymedlop** [comment]
Thanks you
