### ISSUE TITLE
Github client panic v1.3.0

### ISSUE THREAD

**Issue by audrey-mux** [zapier/kubechecks#94]
Hey guys

Just pulled v1.3.0 (new app capability, yay!) - hitting this during pod startup. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29a4a69]

goroutine 1 [running]:
github.com/zapier/kubechecks/pkg/vcs/github_client.CreateGithubClient()
	/src/pkg/vcs/github_client/client.go:76 +0x409
github.com/zapier/kubechecks/cmd.createVCSClient({0xc000058074?, 0x334550f?})
	/src/cmd/vcs.go:16 +0x45
github.com/zapier/kubechecks/cmd.glob..func1(0x58a4ae0?, {0x333c6b4?, 0x0?, 0x0?})
	/src/cmd/controller_cmd.go:30 +0x4a
github.com/spf13/cobra.(*Command).execute(0x58a4ae0, {0x593e390, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x58a50a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/zapier/kubechecks/cmd.Execute()
	/src/cmd/root.go:37 +0xc5
main.main()
	/src/main.go:8 +0x17
```

sorry for being so annoying :-)

**Comment by djeebus** [comment]
Sorry for being so crashy! This is an intereseting one. Your token didn't fail to get a user, but also didn't get a user. Interesting! We can make this safer, but I assume that it'll fail to checkout code, as git won't have a name or email address. What kind of token are you using?

**Comment by audrey-mux** [comment]
Its using a classic PAT, with no admin privs.

**Comment by audrey-mux** [comment]
Ah here we go - the account now needs its email address displayed publicly.

**Comment by SG60** [comment]
> Ah here we go - the account now needs its email address displayed publicly.

Is there any way to use v1.3.0 without a public email address?

**Comment by djeebus** [comment]
Yeah, that was unintentional. Working on the fix now

**Comment by djeebus** [comment]
@audrey-mux would you mind testing the image in #95 and see if that resolves your panic?

**Comment by audrey-mux** [comment]
Looks like it does resolve the issue :-)
